#!/bin/bash

kill-termux() {
    killall com.termux || {
        PID=$$
        while [ -e "/proc/$PID" ]; do
            PID=`/system/bin/ps -p $PID -o ppid= | tr -d " \n"`
        done
        kill $PID
    }
}

googlecamera-cache-save() {
    set -e
    CACHE_PATH="/sdcard/Android/data/com.google.android.GoogleCamera"
    SAVE_PATH="/sdcard/DCIM/googlecamera-cache"
    mkdir "$SAVE_PATH" 2>/dev/null || true
    tar -C "$CACHE_PATH" -vzcf "$SAVE_PATH/googlecamera-cache-$(date +%s).tar.gz" cache
    rm -rf "$CACHE_PATH/cache/"
}

sshd-start-stop() {
    if killall sshd 2> /dev/null; then
        echo -e "\e[1;31mSSHD STOPPED\e[0m"
    else
        sshd
        echo -e "\e[1;32mSSHD STARTED\e[0m"
        echo
        mylocalip
        >&2 echo
        bcast-ip android
    fi
}
